adding middleware for injecting plan in the request
cloudfoundry-incubator/service-fabrik-broker pull request #1097
Opened 2020-10-12 14:08 UTC by jayeshjk

- To handle the cases where incoming request for updates might not contain `plan_id` (e.g., at present update requests coming in from `svcat` don't contain `plan_id`)

2020-10-20 04:24 UTC, vinaybheri commented
Validation on k8s cluster: n-1 is succeeded.

2020-10-20 04:25 UTC, vinaybheri commented
Validation on k8s cluster: n is succeeded.

2020-10-20 04:25 UTC, vinaybheri commented
Validation on k8s cluster: n-2 is succeeded.

2020-10-20 04:34 UTC, vivekzhere requested changes

2020-10-20 04:34 UTC, vivekzhere commented on broker/applications/osb-broker/src/api-controllers/middleware/index.js
> +          resourceId: req.params.instance_id
Need to use getKubernetesName as in #1098

2020-10-29 04:27 UTC, vinaybheri commented
Validation on k8s cluster: n-2 is succeeded.

2020-10-29 04:28 UTC, vinaybheri commented
Validation on k8s cluster: n-1 is succeeded.

2020-10-29 04:28 UTC, vinaybheri commented
Validation on k8s cluster: n is succeeded.

2020-10-29 04:38 UTC, vinaybheri commented
Validation on k8s cluster: n is succeeded.

2020-10-29 06:22 UTC, vivekzhere approved these changes

2020-10-29 07:18 UTC, merged