Delete snapshot only after validation
cloudfoundry-incubator/service-fabrik-broker pull request #1183
Opened 2020-12-18 04:57 UTC by anoopjb

Bug: HCPCFS-2885

2020-12-18 04:58 UTC, anoopjb commented
The test validate-service-fabrik-advanced: test_cross_space_restore/test_validate_cross_space_restore is still failing.

2020-12-22 05:34 UTC, jayeshjk requested changes

2020-12-22 05:34 UTC, jayeshjk commented on broker/data-access-layer/iaas/src/BackupStore.js
> +          this.cloudProvider.deleteSnapshot(data.snapshotId);
missing `return` here.

2020-12-22 16:04 UTC, anoopjb commented on broker/data-access-layer/iaas/src/BackupStore.js
> +          this.cloudProvider.deleteSnapshot(data.snapshotId);
:white_check_mark: Done

2021-01-06 10:37 UTC, jayeshjk approved these changes
LGTM

2021-01-06 10:42 UTC, merged