Add HorizontalPodAutoscaling(HPA) support for interoperator
cloudfoundry-incubator/service-fabrik-broker pull request #1399
Opened 2021-08-13 08:47 UTC by Pooja-08

2021-08-25 07:27 UTC, anoopjb commented on docs/Interoperator-HPA-Observations.md
> +    - [Load test with auto-scaling using the HPA](###Load test the Microservice with auto-scaling using the HPA)
```suggestion
- [Interoperator HPA Observations](#interoperator-hpa-observations)
  - [Abstract](#abstract)
  - [Table of Content](#table-of-content)
  - [Context](#context)
  - [Load Testing](#load-testing)
    - [Load test without auto-scaling](#load-test-without-auto-scaling)
    - [Load test with auto-scaling using the HPA](#load-test-with-auto-scaling-using-the-hpa)
```
We got some broken links.

2021-08-25 07:29 UTC, anoopjb commented on docs/Interoperator-HPA-Observations.md
> +The Horizontal Pod Autoscaler automatically scales the number of the pods, depending on resource utilization like CPU. For example, if we target a 50% CPU utilization for the pods but the pods have a
```suggestion
The Horizontal Pod Autoscaler automatically scales the number of the pods, depending on resource utilization like CPU. For example, if we target a 50% CPU utilization for the pods but the pods have an 80% CPU utilization, the hpa will automatically create new pods. If the CPU utilization falls below 50%, for example, 30%, the hpa terminates pods. This ensures that we always run enough pods but also helps to not waste resources by running too many pods.
Besides CPU utilization, you can also use custom metrics to scale. These custom metrics can be, for example, response time, queue length, or hits-per-second.
```
I prefer the term resources than money 😆

2021-08-25 07:30 UTC, anoopjb commented on docs/Interoperator-HPA-Observations.md
> +RPM-                Requests per minute
```suggestion
RPM -               Requests per minute
```

2021-08-25 08:33 UTC, anoopjb commented on docs/Interoperator-HPA-Observations.md
> +4500 | 300 | 30 | 2 | 6 | 79 | 55 | 1739 | 1208 | 1498 | 11 | worker nodes CPU was increased to 16 to handle the load
```suggestion
500 | 300 | 30 | 2 | 6 | 85 | 45 | 453
300 | 300 | 50 | 2 | 4 | 81 | 29 | 271
500 | 300 | 50 | 2 | 3 | 68 | 63 | 437
500 | 420 | 50 | 2 | 4 | 80 | 58 | 442
4500 | 300 | 30 | 2 | 6 | 79 | 55 | 1739 | 1208 | 1498 | 11 | worker nodes CPU was increased to 16 to handle the load
```
The spaces breaks the table layout.

2021-08-25 08:33 UTC, anoopjb requested changes
Minor cosmetic suggestions.

2021-08-30 06:04 UTC, vinaybheri commented
Validation on k8s cluster: n is succeeded.

2021-08-30 06:07 UTC, vinaybheri commented
Validation on k8s cluster: n+n+n is succeeded.

2021-08-30 06:30 UTC, vinaybheri commented
Validation on k8s cluster: n-1 is succeeded.

2021-08-30 07:31 UTC, anoopjb commented on docs/Interoperator-HPA-Observations.md
> +- [Interoperator HPA Observations](#Interoperator HPA Observations)
```suggestion
- [Interoperator HPA Observations](#interoperator-hpa-observations)
```

2021-08-30 07:38 UTC, anoopjb commented on docs/Interoperator.md
> +  - [Stabilization Window](#Stabilization Window)
```suggestion
- [Interoperator HorizontalPodAutoscaler(HPA)](#interoperator-horizontalpodautoscalerhpa)
  - [Create a Horizontal Pod Autoscaler](#create-a-horizontal-pod-autoscaler)
  - [Deploy the Horizontal Pod Autoscaler](#deploy-the-horizontal-pod-autoscaler)
  - [Default behavior for interoperator HPA](#default-behavior-for-interoperator-hpa)
  - [Scaling Policies](#scaling-policies)
  - [Stabilization Window](#stabilization-window)
```
Spaces doesn't go well with markdown links. 🔗

2021-08-30 07:39 UTC, anoopjb commented on docs/Interoperator.md
> +# Interoperator HorizontalPodAutoscaler(HPA))
```suggestion
# Interoperator HorizontalPodAutoscaler(HPA)
```
Minor typo.

2021-08-30 08:03 UTC, anoopjb commented on docs/Interoperator.md
> +values.yaml file holds the default values. The same can be modified based on the requirement.
```suggestion
[values.yaml](/helm-charts/interoperator/values.yaml) file holds the default values. The same can be modified based on the requirement.
```

2021-08-30 08:05 UTC, anoopjb commented on docs/Interoperator.md
> +To create the Horizontal Pod Autoscaler, paste the following code into the file templates/broker.yaml:
```suggestion
To create the Horizontal Pod Autoscaler, paste the following code into the file [templates/broker.yaml](/helm-charts/interoperator/templates/broker.yaml):

```

2021-08-30 08:08 UTC, anoopjb commented on docs/Interoperator.md
> +** The default values are picked up from the kubernetes doc. Any changes may require a change in the values.yaml file.
```suggestion
** The default values are picked up from the [kubernetes doc](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough). Any changes may require a change in the values.yaml file.
```

2021-08-30 09:37 UTC, anoopjb approved these changes
LGTM

2021-08-30 10:45 UTC, merged