Update plan_id label in CR
cloudfoundry-incubator/service-fabrik-broker pull request #1463
Opened 2021-11-02 11:56 UTC by visargsoneji

The plain_id was not getting updated in case of updateInstance call. This PR fixes that issue!

2021-11-03 08:43 UTC, jintusebastian approved these changes

2021-11-03 08:47 UTC, vinaybheri commented
Validation on k8s cluster: n+n+n failed.

2021-11-03 08:52 UTC, vinaybheri commented
Validation on k8s cluster: n is succeeded.

2021-11-03 12:14 UTC, vinaybheri commented
Validation on k8s cluster: n+n+n failed.

2021-11-03 12:17 UTC, vinaybheri commented
Validation on k8s cluster: n-1 is succeeded.

2021-11-03 13:00 UTC, vinaybheri commented
Validation on k8s cluster: n+n+n failed.

2021-11-03 13:02 UTC, vinaybheri commented
Validation on k8s cluster: n-2 is succeeded.

2021-11-08 05:15 UTC, vinaybheri commented
Validation on k8s cluster: n+n+n failed.

2021-11-08 05:17 UTC, vinaybheri commented
Validation on k8s cluster: n-1 is succeeded.

2021-11-08 05:18 UTC, vinaybheri commented
Validation on k8s cluster: n-2 is succeeded.

2021-11-16 04:42 UTC, anoopjb approved these changes

2021-11-16 04:55 UTC, anoopjb requested changes

2021-11-16 04:55 UTC, anoopjb commented on broker/applications/osb-broker/src/api-controllers/ServiceBrokerApiController.js
> +    labels = _.merge(labels, {
Here were are updating the label whenever we gets a plan update request. But I feel there can be a case when the user sends a wrong plan to update to and our `isUpdatePossible` assertion rejects it. Then we may have a wrong plan id in the label.

2021-11-16 05:00 UTC, anoopjb approved these changes

2021-11-16 05:02 UTC, anoopjb commented on broker/applications/osb-broker/src/api-controllers/ServiceBrokerApiController.js
> +    labels = _.merge(labels, {
Sorry, I realized that we are not applying the label is there are errors. 👍

2021-11-17 11:28 UTC, merged